[TEST] : 뮤지컬 상세 조회 테스트
prgrms-be-devcourse/BE-03-InterMark pull request #103
Opened 2023-01-24 08:13 UTC by rhdtn311

## PR Description 🗒️
closed #101 
- 뮤지컬 상세 조회 테스트 코드를 작성했습니다.

## 추가 사항 및 설명 ➕

## 수정 사항 및 이유 🔄

## To Reviewers 🙏

2023-01-24 08:54 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/service/MusicalFacadeServiceTest.java
> +        assertThrows(EntityNotFoundException.class, () -> musicalFacadeService.findMusicalById(1L));
assertj를 사용하면 assertThatThrownBy를 사용해도 좋을 것 같습니다!!

2023-01-24 08:54 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/service/MusicalFacadeServiceTest.java
> +                .usingRecursiveComparison()
저도 사용해봐야할 것 같네요!! :엄지척

2023-01-24 08:54 UTC, twotwobread reviewed
수고하셨습니다!!

2023-01-24 11:06 UTC, rhdtn311 commented on src/test/java/com/prgrms/be/intermark/domain/musical/service/MusicalFacadeServiceTest.java
> +        assertThrows(EntityNotFoundException.class, () -> musicalFacadeService.findMusicalById(1L));
참고하겠습니다! 감사합니다.

2023-01-24 13:31 UTC, Seongjun-Kwon approved these changes
고생하셨습니다~

2023-01-25 12:06 UTC, park-se-jun requested changes
수정된 코드와 별개로 테스트 로그를 보니 src/main/java/com/prgrms/be/intermark/domain/schedule/controller/ScheduleController.java 의 44 번째 줄에서 error 가 납니다. DeleteMapping이 import 되지 않는것 같아요. 수정 해야할 듯

2023-01-25 12:06 UTC, park-se-jun commented on src/test/java/com/prgrms/be/intermark/domain/musical/service/MusicalFacadeServiceTest.java
> +                .usingRecursiveComparison()
👍️

2023-01-25 14:18 UTC, closed without merging