[REFACTOR] : 변경된 Entity와 유저 로그인 Confilct 해소 및 merge
prgrms-be-devcourse/BE-03-InterMark pull request #125
Opened 2023-01-26 06:40 UTC by twotwobread

## PR Description 🗒️

close #71 
close #11 #27   
close #12 #13 #76 #88 #95 #107 
- 로그인/회원가입 소셜 로그인을 위한 기능 개발
- 유저 조회 관련 기능 개발 및 테스트 코드 작성.
- log 관련 설정
## 추가 사항 및 설명 ➕

- 소셜(구글) 로그인/회원가입 기능 개발 - [twotwobread](https://github.com/twotwobread), [park-se-jun](https://github.com/park-se-jun) 페어프로그래밍
  - SpringSecufityConfig 설정
    - access deny handler 설정. 
    - 정적 파일에 대해 인가 수행하지 않게 구성하고 User 권한을 가진 사람만 /api/v1/** url로 접근할 수 있게 구성.
    - oauth2Login을 이용하게 구성하고 authorization endpoint, authorizationRequestRepository, redirect endpoint, user info endpoint 설정.
    - success handler 설정.
  - 권한 확인 후 엑세스 거부되었을 때 실행될 OAuthAccessDeniedHandler  추가.
    - 상태코드 403과 함께 간단한 text 출력.
  - CookieOAuth2AuthorizationRequestRepository와 CookieUtil 추가.
    - request 정보로부터 Cookie를 가져오는 기능.
    - 쿠키를 저장하는 기능.
    - 쿠키를 삭제하는 기능.
  - CustomIOAuth2UserService와 CustomUserPrincipal 추가.
    - Resource 서버 (구글)로부터 User의 허용된 정보들을 가져오는 부분.
    - 해당 소셜 상의 id, 유저 이름, 유저 역할, 이메일 등의 정보를 가져옴.
    - 해당 정보로 OAuth2User의 구현체인 CustomUserPrincipal 내부 필드값으로 할당하여 반환.
  - success handler인 OAuth2AuthenticationSuccessHandler 추가
    -  실질적으로 우리의 서비스에 유저를 회원가입하는 부분.
      - UserService의 join을 메소드를 이용해서 이미 유저가 존재하면 유저의 변경가능 정보인 user nickname을 업데이트하고 해당 유저 정보를 반환.
      - 유저가 존재하지 않으면 db에 저장하고 해당 유저 정보를 반환
    - 반환된 유저 정보를 이용하여 access token과 refresh token 생성 및 기존 쿠키를 삭제하고 새로운 refresh token 정보를 쿠키에 저장.
    - 인증 성공 반환 정보로 access token을 반환.
  - TokenProvider 추가.
    - access, refresh 토큰을 생성하기 위한 로직 존재.
  - TokenAuthenticationFilter 추가.
    - access toekn과 함께 요청이 들어올 경우 validate 수행하고 인증이 된것이 맞으면 Authentication을 생성하고 SpringSecutiryContext에 저장.
    - 인증되지 않은 경우 그냥 다음 filter 수행.
  - OAuthController
    - 만료된 토큰 refresh를 위해서 /refresh url 컨트롤러 추가. -> 갱신된 토큰 반환.
- 유저 상세 정보 조회 기능 - [twotwobread](https://github.com/twotwobread)
  - isDeleted 상태를 고려하여 repository, service, controller 구현.
  - 성공/실패 관련 test 코드 구현.
- 유저 페이징 조회 기능 - [twotwobread](https://github.com/twotwobread)
  - 현재 페이지 번호가 가능한 마지막 페이지를 넘는 경우를 고려하여 repository, service, controller 구현.
  - 성공/실패 관련 test 코드 구현.
- log 관련 설정. - [twotwobread](https://github.com/twotwobread)
  - logback 로그 메시지 패턴 설정.
  - aws clock watch에 해당 로그가 쌓일 수 있게 설정. 

## To Reviewers 🙏

- squash and merge 기능 때문에 커밋이 안보일꺼 같애서 최대한 자세히 적었습니다!!

2023-01-26 09:04 UTC, rhdtn311 approved these changes
고생하셨습니다!!

2023-01-26 14:23 UTC, Seongjun-Kwon approved these changes
고생 많으셨습니다~
현재 develop 이랑 버전이 다른 부분들이 좀 보입니다
merge 하기 전에 pull 해서 해결 부탁드려용

2023-01-26 14:23 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/intermark/auth/OAuth2AuthenticationSuccessHandler.java
> +        return "{\"token\":\"" + accessToken + "\"}";
다른 방식이 없을까요?

2023-01-26 14:23 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/intermark/domain/ticket/dto/TicketDeleteResponseDto.java
> +}
이거는 현재 develop 에서는 없는 파일이에용

2023-01-26 14:23 UTC, Seongjun-Kwon commented on src/main/resources/application.yml
> +    password: intermark123!
가리면 좋을 것 같아요

2023-01-27 05:49 UTC, twotwobread commented on src/main/java/com/prgrms/be/intermark/auth/OAuth2AuthenticationSuccessHandler.java
> +        return "{\"token\":\"" + accessToken + "\"}";
ObjectMapper를 이용하여 json body 정보를 만들어서 response에 넣어주도록 수정하였습니다!!

2023-01-27 09:39 UTC, park-se-jun requested changes
일단 눈에보이는 오류들에 대해 적어봤습니다. 혼자 하기 힘들면 패프로 같이 ㄱ?

2023-01-27 09:39 UTC, park-se-jun commented on src/main/java/com/prgrms/be/intermark/common/dto/page/PageListIndexSize.java
> +package com.prgrms.be.intermark.common.dto.page;
PageListIndexSize와 PaeResponseDto는 develop 브랜치에서 common.dto.page.dto 안에 있으므로 그렇게 변경하는게 좋아 보입니다.(다른곳에서도 다 그렇게 참조해서 오류남)

2023-01-27 09:39 UTC, park-se-jun commented on src/main/java/com/prgrms/be/intermark/common/dto/page/PageResponseDTO.java
> +package com.prgrms.be.intermark.common.dto.page;
PageListIndexSize와 PaeResponseDto는 develop 브랜치에서 common.dto.page.dto 안에 있으므로 그렇게 변경하는게 좋아 보입니다.(다른곳에서도 다 그렇게 참조해서 오류남)

2023-01-27 09:39 UTC, park-se-jun commented on src/main/java/com/prgrms/be/intermark/domain/user/service/UserService.java
> +                PageListIndexSize.ADMIN_PERFORMANCE_LIST_INDEX_SIZE);
현재 코드에는 이곳에 해당하는 내용이 PageListIndexSize에 없습니다. 추가해 주세요. 짱수영님

2023-01-27 09:39 UTC, park-se-jun commented on src/main/java/com/prgrms/be/intermark/domain/user/repository/UserRepository.java
> +    Optional<User> findByIdAndIsDeletedFalse(Long userId);
ticketService의 43번째 줄에 이 함수와 같은 역할을 하지만 메소드 명이 다른 함수가 있습니다. 2중 1개로 통일시켜 주세요.

https://github.com/prgrms-be-devcourse/BE-03-InterMark/blob/52ef3253151b59a31fa76ec0df0df286d5661fe9/src/main/java/com/prgrms/be/intermark/domain/ticket/service/TicketService.java#L43

2023-01-27 09:39 UTC, park-se-jun commented on src/main/java/com/prgrms/be/intermark/domain/user/service/UserService.java
> +    public UserInfoResponseDTO findById(Long userId) {
이게 아까 성준이형한테 말한 부분! 
https://github.com/prgrms-be-devcourse/BE-03-InterMark/blob/52ef3253151b59a31fa76ec0df0df286d5661fe9/src/main/java/com/prgrms/be/intermark/domain/musical/service/MusicalFacadeService.java#L59
랑 일치하지 않는 return 값을 가지고 있네용.

아까 말 나온대로 facade 패턴을 위한 메소드를 하나 만들어서 그쪽 메소드의 이름을 그걸로다가 바꾸면 되지 않을까 싶습니당.

2023-01-28 08:08 UTC, park-se-jun reviewed
핸들러 겹치는 것만 해결 하면 일단 문제는 없을 것 같기두 합니다. 제가 올렸던 application.yml을 좀 수정하긴 할듯

해당 변경사항과 별개로 uploadImageServiceImpl의 ${file.images} 여러가지 에로사항이 있는것 같던데 이건 그냥 application.yml에 저걸 바꾸기 전까지 file.images를 추가하는게 나을 것 같음

p.s gitignore에 application*.yml 있는디 기본적인 yml은 있는게 편할 거같아서 제꺼 pr에서 기본적인 yml 을 올리니 yml을 없는 현 상태에서 해당 구문을 빼는건 어떨지 건의 드립니다

2023-01-28 08:08 UTC, park-se-jun commented on src/main/java/com/prgrms/be/intermark/common/exception/GlobalControllerAdvice.java
> +	public ErrorResponse entityNotFoundExceptionHandler(EntityNotFoundException exception) {
29번째 줄과88번째 줄 2곳에서 쓰여서 컴파일시 에러가 발생합니다.

https://github.com/prgrms-be-devcourse/BE-03-InterMark/blob/e31af808cb71a3ef41d917ec166b40a9cc165c0c/src/main/java/com/prgrms/be/intermark/common/exception/GlobalControllerAdvice.java#L88

2023-01-28 08:08 UTC, park-se-jun approved these changes

2023-01-28 09:41 UTC, twotwobread commented
> 핸들러 겹치는 것만 해결 하면 일단 문제는 없을 것 같기두 합니다. 제가 올렸던 application.yml을 좀 수정하긴 할듯
> 
> 해당 변경사항과 별개로 uploadImageServiceImpl의 ${file.images} 여러가지 에로사항이 있는것 같던데 이건 그냥 application.yml에 저걸 바꾸기 전까지 file.images를 추가하는게 나을 것 같음
> 
> p.s gitignore에 application*.yml 있는디 기본적인 yml은 있는게 편할 거같아서 제꺼 pr에서 기본적인 yml 을 올리니 yml을 없는 현 상태에서 해당 구문을 빼는건 어떨지 건의 드립니다

gitignore에서 뺐습니다!!

2023-01-28 09:48 UTC, merged