[FEAT] : 뮤지컬 등록 시 이미지 S3 에 저장하도록 구현
prgrms-be-devcourse/BE-03-InterMark pull request #127
Opened 2023-01-26 11:36 UTC by Seongjun-Kwon

## PR Description 🗒️
closed #118 

- 뮤지컬 등록 시 이미지 S3 에 저장하도록 구현하였습니다.

## 추가 사항 및 설명 ➕
- 팀원들끼리 profile 에 대한 협의를 하지 않아서 일단 @Primary 를 S3ImageUploadService 에 달아주었습니다.
- ImageUploadService 를 뮤지컬 등록에만 종속되지 않도록 구현해보았습니다.

## 수정 사항 및 이유 🔄

## To Reviewers 🙏

2023-01-27 09:08 UTC, twotwobread approved these changes
수고하셨습니다!

2023-01-27 17:51 UTC, rhdtn311 approved these changes
고생하셨습니다.

2023-01-29 07:08 UTC, park-se-jun requested changes
짱준이형인 고생 너무 많았고 로컬에서 최신 develop 이랑 merge 한버 해서 confilct 해소하고 push 하고 다시 알려주세요

2023-01-29 11:51 UTC, park-se-jun approved these changes

2023-01-29 12:17 UTC, merged