[TEST] : 뮤지컬 상세 조회 테스트
prgrms-be-devcourse/BE-03-InterMark pull request #130
Opened 2023-01-27 18:28 UTC by rhdtn311

## PR Description 🗒️
- 뮤지컬 상세 조회 테스트코드 작성

## 추가 사항 및 설명 ➕

## 수정 사항 및 이유 🔄

## To Reviewers 🙏

2023-01-28 12:00 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/controller/MusicalControllerTest.java
> +                .andDo(document("Find Musical Detail",
document identifier 이름도 컨벤션이 필요할꺼 같슴다아,,,

2023-01-28 12:02 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/controller/MusicalControllerTest.java
> +        MvcResult mvcResult = resultActions.andExpect(status().isOk())
mvcResult가 있는 이유는 뭔가요?? 변수가 없어도 괜찮지 않을까요?

2023-01-28 12:03 UTC, twotwobread approved these changes
수고하셨습니다!!

2023-01-29 07:13 UTC, park-se-jun requested changes
테스트코드 너무 멋지고~
변경된 develop이랑 local merge 하고 conflict 해소 해서 push 해주세용!(테스트 제대로 될거임 안되면 불러주셈. 코드 커버리지도 댓글로 보입니당)

2023-01-29 13:17 UTC, Seongjun-Kwon approved these changes
고생하셨습니다~

2023-01-30 08:44 UTC, park-se-jun approved these changes

2023-01-30 08:46 UTC, merged