[TEST] : 티켓 예매 등록 API 테스트
prgrms-be-devcourse/BE-03-InterMark pull request #132
Opened 2023-01-28 09:34 UTC by rhdtn311

## PR Description 🗒️
- 티켓 에몌 등록 API 테스트 코드를 작성하였습니다.

## 추가 사항 및 설명 ➕
- 예매 성공, 실패에 대한 서비스 레이어 단위 테스트, 통합 테스트, 컨트롤러 테스트 코드를 작성하였습니다.

## 수정 사항 및 이유 🔄

## To Reviewers 🙏

2023-01-28 12:05 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/ticket/controller/TicketControllerTest.java
> +    void getAllMusicalsSuccess() throws Exception {
예매 등록 실패 관련해서는 문서화 해야하는 상황이 없을까요??

2023-01-28 12:06 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/ticket/service/TicketServiceIntegrationTest.java
> +        Assertions.assertThat(ticketId).isEqualTo(ticket.getId());
assertThat도 static으로 등록해도 좋을 것 같습니다.

2023-01-28 12:08 UTC, twotwobread approved these changes
수고하셨습니다!!

2023-01-29 07:15 UTC, park-se-jun requested changes
변경된 develop 과local에서 merge해 테스트가 여전히 잘 되는지 확인해 주시고, 잘 되면 카톡으로 다시 알려주세용

2023-01-29 13:19 UTC, Seongjun-Kwon approved these changes
고생하셨습니다~

2023-01-30 11:09 UTC, park-se-jun approved these changes

2023-01-30 11:29 UTC, merged