[TEST] : 회원 레포지토리, 서비스 테스트 및 RestDocs
prgrms-be-devcourse/BE-03-InterMark pull request #134
Opened 2023-01-28 11:48 UTC by twotwobread

## PR Description 🗒️
close #133 

- User 레포지토리, 서비스 메소드 테스트 코드 추가.
- UserController RestDocs 적용.
## 추가 사항 및 설명 ➕

- 인증/인가, 회원 조회 로직에서 사용되는 추가된 쿼리 메소드들에 대한 테스트
  - `findBySocialTypeAndSocialId` 테스트 작성
  - `findByIdAndRefreshToken` 테스트 작성
  - `countByIsDeletedFalse` 테스트 작성
- 유저 서비스 테스트
  - `join` 회원 존재 유무에 따라 로그인/ 회원가입을 진행하는 메소드에 대한 테스트
  - `findByProviderAndProviderId` 소셜 로그인 provider와 해당 서버로부터 받은 id를 이용하여 유저 조회하는 메소드에 대한 테스트
  - `findByIdFasade` Fasade 계층에서 유저 조회를 하기 위한 메소드에 대한 테스트
- 유저 컨트롤러 RestDocs 적용

2023-01-29 07:19 UTC, park-se-jun requested changes
test 가 잡다한 문제(71번과 merge 하면서 발생한 크고 작은 차이점들) 때문에 오류가 납니다. develop 의 변경사항을 local에서 merge 하고 test 결과를 보고 push 하면 테스트가 잘 통과하는지 알 수 있으니 그렇게 해주시고 다시 알려주세요 수영쿤👍️

2023-01-29 13:20 UTC, Seongjun-Kwon approved these changes
고생하셨습니다~

2023-01-29 14:00 UTC, twotwobread commented
> test 가 잡다한 문제(71번과 merge 하면서 발생한 크고 작은 차이점들) 때문에 오류가 납니다. develop 의 변경사항을 local에서 merge 하고 test 결과를 보고 push 하면 테스트가 잘 통과하는지 알 수 있으니 그렇게 해주시고 다시 알려주세요 수영쿤👍️

![image](https://user-images.githubusercontent.com/78334910/215331089-804cc657-ba69-4c79-bd1e-997994982793.png)
모든 테스트 통과하는 것을 확인했습니다!!

2023-01-30 11:36 UTC, park-se-jun approved these changes

2023-01-30 22:15 UTC, merged