[TEST] : 뮤지컬 등록 테스트
prgrms-be-devcourse/BE-03-InterMark pull request #143
Opened 2023-01-29 11:35 UTC by Seongjun-Kwon

## PR Description 🗒️
closed #64 

- 뮤지컬 등록 테스트 입니다.

## 추가 사항 및 설명 ➕

## 수정 사항 및 이유 🔄

## To Reviewers 🙏

2023-01-30 21:53 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/stadium/service/StadiumServiceTest.java
> +				.isInstanceOf(EntityNotFoundException.class);
isInstanceOf 쓰면 상속받은 예외들도 통과하는걸로 알아서 부모 예외 클래스 확인을 위한 부분이 아니라면 isExactlyInstanceOf를 사용하는 것도 좋을 것 같습니다!

2023-01-30 21:57 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/seatgrade/repository/SeatGradeRepositoryTest.java
> +            assertThat(savedSeatGrade)
반환되는 객체로 비교하면 무조건 같을 수 밖에 없고 id를 무시해야 하니까 조회를 해서 비교해보는건 어떨까요??

2023-01-30 21:59 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/seatgrade/repository/SeatGradeRepositoryTest.java
> +        @NullAndEmptySource
ParameterizedTest에서 null 값을 못써서 로직 상에서 그냥 값을 넣어서 테스트 했는데 요거 써봐야겠슴다!

2023-01-30 22:02 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical_seat/repository/MusicalSeatRepositoryTest.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
:엄지척

2023-01-30 22:06 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/service/MusicalFacadeServiceTest.java
> +        assertThat(musicalId).isNotNull();
musicalId가 널이 아니다가 등록에 성공했다의 기준이 될 수 있을지 잘 모르겠습니다. 조회를 해서 해당 musicalId의 정보가 내가 넣은 정보랑 같은지 확인했을 때 알 수 있지 않을까요??

2023-01-30 22:10 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/controller/MusicalControllerTest.java
> +    @DisplayName("성공 - 정상적인 뮤지컬 값이 들어오면 등록에 성공한다 - createMusical")
컨벤션이 한글 성공이 아닌 Success인 것으로 알고 있습니다.

2023-01-30 22:10 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/controller/MusicalControllerTest.java
> +    @WithMockUser(username = "1", roles = {"USER"}, password = "")
모든 메소드에 붙이실꺼면 클래스 단에 하나 붙여도 동일하게 동작합니다.

2023-01-30 22:11 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/casting/repository/CastingRepositoryTest.java
> +        @DisplayName("실패 - 연관된 배우 값이 없으면 저장에 실패한다")
여기도 컨벤션이 Fail, Success로 영어로 알고 있습니다

2023-01-30 22:13 UTC, twotwobread requested changes
변경 파일이 많을 때는 PR에 To Reviewers 부분에서 어떤 파일을 중점적으로 코드리뷰 했으면 하는지를 적어주면 좋을 것 같습니다!! 앞으로 저도 그렇게 하겠습니다. :꾸벅
고생하셨습니다아 고칠 부분 고쳐주세요!!

2023-01-31 07:34 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/intermark/domain/stadium/service/StadiumServiceTest.java
> +				.isInstanceOf(EntityNotFoundException.class);
감사합니다. 반영했습니다.

2023-01-31 09:24 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/intermark/domain/musical/controller/MusicalControllerTest.java
> +    @DisplayName("성공 - 정상적인 뮤지컬 값이 들어오면 등록에 성공한다 - createMusical")
수정했습니다

2023-01-31 09:25 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/intermark/domain/casting/repository/CastingRepositoryTest.java
> +        @DisplayName("실패 - 연관된 배우 값이 없으면 저장에 실패한다")
반영했습니다

2023-01-31 09:31 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/intermark/domain/musical/controller/MusicalControllerTest.java
> +    @WithMockUser(username = "1", roles = {"USER"}, password = "")
반영하였습니다

2023-01-31 09:50 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/intermark/domain/seatgrade/repository/SeatGradeRepositoryTest.java
> +            assertThat(savedSeatGrade)
입력되는 객체와 저장된 객체의 필드 값이 같은 지를 비교하려고 이와 같이 작성하였습니다.

저장이 되었는지를 여부를 확인하고자 한다면 수영님이 말씀하신대로 하는 것이 좋아보입니다.
반영하였습니다

2023-01-31 09:58 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/intermark/domain/musical/service/MusicalFacadeServiceTest.java
> +        assertThat(musicalId).isNotNull();
반영했습니다

2023-01-31 10:09 UTC, rhdtn311 commented on src/main/java/com/prgrms/be/intermark/domain/user/User.java
>      }
`setNickname()`에서 `isDeleted`, `birth`, `email`까지 초기화하는 이유가 무엇인가요? 어떤 역할을 하는건지 궁금합니다.

2023-01-31 10:11 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/intermark/domain/user/User.java
>      }
와 이거 develop 에서 pull 하다가 실수한거 같아요 ㄷㄷ
태현님 신이신가요?

2023-01-31 10:23 UTC, twotwobread approved these changes
수고하셨습니다!!

2023-01-31 10:27 UTC, rhdtn311 approved these changes
고생하셨습니다~

2023-01-31 11:45 UTC, merged