[TEST] : 뮤지컬 삭제 테스트
prgrms-be-devcourse/BE-03-InterMark pull request #146
Opened 2023-01-30 20:21 UTC by Seongjun-Kwon

## PR Description 🗒️
closed #65 

- 뮤지컬 삭제 테스트입니다.
- 뮤지컬 삭제에 필요한 서비스들 테스트도 포함하였습니다.

## 추가 사항 및 설명 ➕

## 수정 사항 및 이유 🔄

## To Reviewers 🙏

2023-01-30 22:17 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/casting/repository/CastingRepositoryTest.java
> +    @DisplayName("save")
PR이 뮤지컬 삭제 테스트인데 Casting 등록 테스트가 있는 것보다 뮤지컬 삭제 테스트에 대한 내용만 있는 것이 좋을 것 같습니다!!

2023-01-30 22:21 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/repository/MusicalRepositoryTest.java
> +        @ParameterizedTest
Nested랑 ParameterizedTest를 같이 쓸 수 있군요?! 안된다고 해서 안되는줄 알았습니다. :엄지척

2023-01-30 22:22 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/repository/MusicalRepositoryTest.java
> +    @DisplayName("save")
이것도 뮤지컬 등록 테스트 PR에 속하는 것이 좋을 것 같습니다!

2023-01-30 22:23 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/repository/MusicalRepositoryTest.java
> +        @DisplayName("성공 - 올바른 값이 들어오면 뮤지컬을 저장한다")
컨벤션이 맨 앞에 성공 유무를 Success/Fail 영어로 표기하기로 했습니다!

2023-01-30 22:26 UTC, twotwobread commented on src/test/java/com/prgrms/be/intermark/domain/musical/service/MusicalDetailImageServiceTest.java
> +            verify(musicalDetailImageRepository).findByMusicalAndIsDeletedIsFalse(musical);
모킹을 이용한 단위 테스트에서 for문을 통해서 내부에서 어떤 동작이 수행되는지 체크할 필요가 있을까요?? for문의 부분은 레포지토리 단위 테스트에서 체크해도 좋지 않을까요??

2023-01-30 22:29 UTC, twotwobread requested changes
수고하셨습니다. 컨벤션 부분은 다 바꿔주시면 좋을 것 같습니다!!

2023-01-31 10:03 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/intermark/domain/casting/repository/CastingRepositoryTest.java
> +    @DisplayName("save")
죄송합니다.
뮤지컬 등록 테스트 pr 내용이 필요해서 pull 해서 쓰다보니 파일이 많아졌네요

2023-01-31 10:03 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/intermark/domain/musical/repository/MusicalRepositoryTest.java
> +    @DisplayName("save")
죄송합니다.
뮤지컬 등록 테스트 pr 내용이 필요해서 pull 해서 쓰다보니 파일이 많아졌네요

2023-01-31 10:30 UTC, rhdtn311 approved these changes
고생하셨습니다~

2023-01-31 12:26 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/intermark/domain/musical/repository/MusicalRepositoryTest.java
> +        @DisplayName("성공 - 올바른 값이 들어오면 뮤지컬을 저장한다")
수정했습니다.

2023-01-31 14:34 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/intermark/domain/musical/service/MusicalDetailImageServiceTest.java
> +            verify(musicalDetailImageRepository).findByMusicalAndIsDeletedIsFalse(musical);
MusicalDetailService 의 deleteAllByMusical 호출 시에 함께 호출되는 메서드라 deleteAllByMusical 호출 시 동작하는지 여부를 검증하기 위해 넣어놓았습니다!

2023-01-31 14:43 UTC, twotwobread approved these changes
수고하셨습니다!!

2023-01-31 14:43 UTC, merged